_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.8
            "5": 0.18.1
            "6": 4.44.0
            "8":
                - 1
                - 5
            "12": 0.18.1
            "13": linux-x86_64
epochs:
    value:
        - 8
learning_rate:
    value:
        - 0.0001
optimizer_gamma:
    value:
        - 0.1
step_size:
    value:
        - 30
