wandb_version: 1

learning_rate:
  desc: null
  value:
  - 0.0001
step_size:
  desc: null
  value:
  - 30
epochs:
  desc: null
  value:
  - 8
optimizer_gamma:
  desc: null
  value:
  - 0.1
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.44.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1726811107
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.8
      5: 0.17.8
      6: 4.44.0
      8:
      - 1
      - 5
      13: linux-x86_64
